server {
    listen 80;
    server_name jludate.com www.jludate.com;
    # 强制将所有 HTTP 请求跳转到 HTTPS，保护吉大同学的隐私
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name jludate.com www.jludate.com;

    # 这里的路径必须和你在 docker-compose.yml 里挂载的路径完全一致
    ssl_certificate /etc/nginx/certs/jludate_origin.pem;
    ssl_certificate_key /etc/nginx/certs/jludate_origin.key;

    # 安全加固：只使用安全的协议和加密算法
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

     # 前端界面：给同学们看的漂亮网页
    location / {
        proxy_pass http://frontend:80; 
        proxy_set_header Host $host;
    }

    # 后端接口：给手机和网页传数据的后台
    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }
}